Return-Path: <linux-aspeed+bounces-785-lists+linux-aspeed=lfdr.de@lists.ozlabs.org>
X-Original-To: lists+linux-aspeed@lfdr.de
Delivered-To: lists+linux-aspeed@lfdr.de
Received: from lists.ozlabs.org (lists.ozlabs.org [112.213.38.117])
	by mail.lfdr.de (Postfix) with ESMTPS id BAE28A3CE30
	for <lists+linux-aspeed@lfdr.de>; Thu, 20 Feb 2025 01:41:21 +0100 (CET)
Received: from boromir.ozlabs.org (localhost [127.0.0.1])
	by lists.ozlabs.org (Postfix) with ESMTP id 4YyvZb2KyLz2yYJ;
	Thu, 20 Feb 2025 11:41:11 +1100 (AEDT)
X-Original-To: linux-aspeed@lists.ozlabs.org
Authentication-Results: lists.ozlabs.org; arc=none smtp.remote-ip=203.29.241.158
ARC-Seal: i=1; a=rsa-sha256; d=lists.ozlabs.org; s=201707; t=1740012071;
	cv=none; b=GwbPq7K1WcrEyBkLBA8A5OGvtxtSBMCSuZLJN6vQO9qNcl6StCMVrsX/kst/NGUzs8YGkH0V5gJJrMckdeLSyA2ErRcJ5/cBvNsOnwqu5TuIgY32rMsHiZNe/r2o4G8YnSV59pxA1u660ehhF4yWou9LTE0+LLSmQDySV5s0hnfe0Gl3oFIrhyMhB2e/7RCmtb+7pN9sj8+vi11fyCogFlLhgLjxFWFJo/MJ+3jhT6DuutgSrcu7TRzKmsXHcE6jOhxZu/IFPGLoYrEoCSXNub2zQdkHWFzQuxe1vvSAe+qL9F7jWCuN8AV29Mw0Mqy1owEed+mFFQwl+/26rI4uaQ==
ARC-Message-Signature: i=1; a=rsa-sha256; d=lists.ozlabs.org; s=201707;
	t=1740012071; c=relaxed/relaxed;
	bh=hBvUhOI2FL6RYIJ2THi32kx7sgjzdUmW5yq1BzGPFao=;
	h=Message-ID:Subject:From:To:Cc:Date:In-Reply-To:References:
	 Content-Type:MIME-Version; b=Brc1V48iuM2Q1gwARN5unlmLJ2jTszuCU0jYIPya/yanScTsjsJqUXQkgp8FfJRPYUa86MjQrJZq2WHCV1UV/oknsKU9fFebeZHpS/47tqLzs92ZjXZZs16Agp5BOAhJMjsc/1sLPxqzyIgLvBlhtVvw/tVDLrqi7ikdwaxAjDl04PASaZOAoJIP4eEEnN2ObBT6Jp1r0HRU+zqFANPscqm7ZkZGHWbcl/cUJVUKNejwc6sFFUtDQJkMHMQjdrwlQ9gtTBl2J3ecjKH4oMvGemID1hSEdwsNY4Itw1mOhoG4WwcDYAbiFCWCOiwRoMmQRHC5dFeUMrRlFz9NumgGug==
ARC-Authentication-Results: i=1; lists.ozlabs.org; dmarc=pass (p=none dis=none) header.from=codeconstruct.com.au; dkim=pass (2048-bit key; unprotected) header.d=codeconstruct.com.au header.i=@codeconstruct.com.au header.a=rsa-sha256 header.s=2022a header.b=nCRRlhV3; dkim-atps=neutral; spf=pass (client-ip=203.29.241.158; helo=codeconstruct.com.au; envelope-from=andrew@codeconstruct.com.au; receiver=lists.ozlabs.org) smtp.mailfrom=codeconstruct.com.au
Authentication-Results: lists.ozlabs.org; dmarc=pass (p=none dis=none) header.from=codeconstruct.com.au
Authentication-Results: lists.ozlabs.org;
	dkim=pass (2048-bit key; unprotected) header.d=codeconstruct.com.au header.i=@codeconstruct.com.au header.a=rsa-sha256 header.s=2022a header.b=nCRRlhV3;
	dkim-atps=neutral
Authentication-Results: lists.ozlabs.org; spf=pass (sender SPF authorized) smtp.mailfrom=codeconstruct.com.au (client-ip=203.29.241.158; helo=codeconstruct.com.au; envelope-from=andrew@codeconstruct.com.au; receiver=lists.ozlabs.org)
Received: from codeconstruct.com.au (pi.codeconstruct.com.au [203.29.241.158])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(No client certificate requested)
	by lists.ozlabs.org (Postfix) with ESMTPS id 4YyvZX6XD0z2yFB
	for <linux-aspeed@lists.ozlabs.org>; Thu, 20 Feb 2025 11:41:08 +1100 (AEDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
	d=codeconstruct.com.au; s=2022a; t=1740012067;
	bh=hBvUhOI2FL6RYIJ2THi32kx7sgjzdUmW5yq1BzGPFao=;
	h=Subject:From:To:Cc:Date:In-Reply-To:References;
	b=nCRRlhV3RL8kHlRzrBz9xbUtPiDC8GRXo00VXtOwMfmx0z5NU+akRBi6RHHd+nAlg
	 cP2qdK3lk9Vnjc6I7EQJ3tCJSwrCYJHyggdFfzeYRF9hnC8ErxhqZFRnQPSY8VBO6h
	 mD33h31kJBPsXCKVkhFdw3U63WRuPA8rOaaShgTTotwhXaM4yXrMLsqlsFkClrSzQD
	 jm3huJ7p/OwT3dMEZVV1ow+FdSQ1hunHbhvgegvT4LOrMdxjwRBayFzp+DWCKqmQ3L
	 Q1Tqa3O+ekfB5FTPuzSRSURLeDMTeaOIy3iDSgWay4DqZtKGKkOo1VMxdLiX2IPFwx
	 2LvhUgAf4iy7g==
Received: from [192.168.68.112] (ppp118-210-187-53.adl-adc-lon-bras34.tpg.internode.on.net [118.210.187.53])
	by mail.codeconstruct.com.au (Postfix) with ESMTPSA id 2B29F75FE6;
	Thu, 20 Feb 2025 08:41:06 +0800 (AWST)
Message-ID: <379b87b84ae79ce6cb49ee27410e628518e0e269.camel@codeconstruct.com.au>
Subject: Re: [PATCH 3/3] ARM: dts: aspeed: Add Balcones system
From: Andrew Jeffery <andrew@codeconstruct.com.au>
To: Eddie James <eajames@linux.ibm.com>, linux-aspeed@lists.ozlabs.org
Cc: robh@kernel.org, krzk+dt@kernel.org, conor+dt@kernel.org, 
	devicetree@vger.kernel.org
Date: Thu, 20 Feb 2025 11:11:05 +1030
In-Reply-To: <20250219212735.1365050-4-eajames@linux.ibm.com>
References: <20250219212735.1365050-1-eajames@linux.ibm.com>
	 <20250219212735.1365050-4-eajames@linux.ibm.com>
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64
User-Agent: Evolution 3.46.4-2 
X-Mailing-List: linux-aspeed@lists.ozlabs.org
List-Id: <linux-aspeed.lists.ozlabs.org>
List-Help: <mailto:linux-aspeed+help@lists.ozlabs.org>
List-Owner: <mailto:linux-aspeed+owner@lists.ozlabs.org>
List-Post: <mailto:linux-aspeed@lists.ozlabs.org>
List-Archive: <https://lore.kernel.org/linux-aspeed/>,
  <https://lists.ozlabs.org/pipermail/linux-aspeed/>
List-Subscribe: <mailto:linux-aspeed+subscribe@lists.ozlabs.org>,
  <mailto:linux-aspeed+subscribe-digest@lists.ozlabs.org>,
  <mailto:linux-aspeed+subscribe-nomail@lists.ozlabs.org>
List-Unsubscribe: <mailto:linux-aspeed+unsubscribe@lists.ozlabs.org>
MIME-Version: 1.0
X-Spam-Status: No, score=-0.2 required=5.0 tests=DKIM_SIGNED,DKIM_VALID,
	DKIM_VALID_AU,DKIM_VALID_EF,SPF_HELO_PASS,SPF_PASS autolearn=disabled
	version=4.0.0
X-Spam-Checker-Version: SpamAssassin 4.0.0 (2022-12-13) on lists.ozlabs.org

SGkgRWRkaWUsCgpJIGhhdmUgc29tZSBtaW5vciBjb21tZW50cyBpbmxpbmU6CgpPbiBXZWQsIDIw
MjUtMDItMTkgYXQgMTU6MjcgLTA2MDAsIEVkZGllIEphbWVzIHdyb3RlOgo+IFRoZSBCYWxjb25l
cyBzeXN0ZW0gaXMgc2ltaWxhciB0byBCb25uZWxsIGJ1dCB3aXRoIGEgUE9XRVIxMSBwcm9jZXNz
b3IuCgpDYW4geW91IGFkZCBzb21lIGNvbW1lbnRhcnkgYWJvdXQgdGhlIFAxMSBkdWFsIHZzIHF1
YWQgY2hhbmdlcyBoZXJlPwoKPiAKPiBTaWduZWQtb2ZmLWJ5OiBFZGRpZSBKYW1lcyA8ZWFqYW1l
c0BsaW51eC5pYm0uY29tPgo+IC0tLQo+IMKgYXJjaC9hcm0vYm9vdC9kdHMvYXNwZWVkL01ha2Vm
aWxlwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgIHzCoMKgIDEgKwo+IMKgLi4uL2R0cy9hc3BlZWQv
YXNwZWVkLWJtYy1pYm0tYmFsY29uZXMuZHRzwqDCoMKgIHwgNTk0ICsrKysrKysrKysrKysKPiDC
oC4uLi9hcm0vYm9vdC9kdHMvYXNwZWVkL2libS1wb3dlcjExLWR1YWwuZHRzaSB8IDc3OSArKysr
KysrKysrKysrKysrKysKPiDCoC4uLi9hcm0vYm9vdC9kdHMvYXNwZWVkL2libS1wb3dlcjExLXF1
YWQuZHRzaSB8IDc2OSArLS0tLS0tLS0tLS0tLS0tLQo+IMKgNCBmaWxlcyBjaGFuZ2VkLCAxMzc2
IGluc2VydGlvbnMoKyksIDc2NyBkZWxldGlvbnMoLSkKPiDCoGNyZWF0ZSBtb2RlIDEwMDY0NCBh
cmNoL2FybS9ib290L2R0cy9hc3BlZWQvYXNwZWVkLWJtYy1pYm0tYmFsY29uZXMuZHRzCj4gwqBj
cmVhdGUgbW9kZSAxMDA2NDQgYXJjaC9hcm0vYm9vdC9kdHMvYXNwZWVkL2libS1wb3dlcjExLWR1
YWwuZHRzaQo+IAo+IGRpZmYgLS1naXQgYS9hcmNoL2FybS9ib290L2R0cy9hc3BlZWQvTWFrZWZp
bGUgYi9hcmNoL2FybS9ib290L2R0cy9hc3BlZWQvTWFrZWZpbGUKPiBpbmRleCAyZTVmNDgzM2Ew
NzNiLi43MWIyZDY3ZmRiYWM4IDEwMDY0NAo+IC0tLSBhL2FyY2gvYXJtL2Jvb3QvZHRzL2FzcGVl
ZC9NYWtlZmlsZQo+ICsrKyBiL2FyY2gvYXJtL2Jvb3QvZHRzL2FzcGVlZC9NYWtlZmlsZQo+IEBA
IC0zNCw2ICszNCw3IEBAIGR0Yi0kKENPTkZJR19BUkNIX0FTUEVFRCkgKz0gXAo+IMKgwqDCoMKg
wqDCoMKgwqBhc3BlZWQtYm1jLWZhY2Vib29rLXlhbXAuZHRiIFwKPiDCoMKgwqDCoMKgwqDCoMKg
YXNwZWVkLWJtYy1mYWNlYm9vay15b3NlbWl0ZXYyLmR0YiBcCj4gwqDCoMKgwqDCoMKgwqDCoGFz
cGVlZC1ibWMtZmFjZWJvb2steW9zZW1pdGU0LmR0YiBcCj4gK8KgwqDCoMKgwqDCoMKgYXNwZWVk
LWJtYy1pYm0tYmFsY29uZXMuZHRiIFwKPiDCoMKgwqDCoMKgwqDCoMKgYXNwZWVkLWJtYy1pYm0t
Ymx1ZXJpZGdlLmR0YiBcCj4gwqDCoMKgwqDCoMKgwqDCoGFzcGVlZC1ibWMtaWJtLWJvbm5lbGwu
ZHRiIFwKPiDCoMKgwqDCoMKgwqDCoMKgYXNwZWVkLWJtYy1pYm0tZXZlcmVzdC5kdGIgXAo+IGRp
ZmYgLS1naXQgYS9hcmNoL2FybS9ib290L2R0cy9hc3BlZWQvYXNwZWVkLWJtYy1pYm0tYmFsY29u
ZXMuZHRzIGIvYXJjaC9hcm0vYm9vdC9kdHMvYXNwZWVkL2FzcGVlZC1ibWMtaWJtLWJhbGNvbmVz
LmR0cwo+IG5ldyBmaWxlIG1vZGUgMTAwNjQ0Cj4gaW5kZXggMDAwMDAwMDAwMDAwMC4uMGZlOTlh
NzQ4YjYzYgo+IC0tLSAvZGV2L251bGwKPiArKysgYi9hcmNoL2FybS9ib290L2R0cy9hc3BlZWQv
YXNwZWVkLWJtYy1pYm0tYmFsY29uZXMuZHRzCj4gQEAgLTAsMCArMSw1OTQgQEAKPiArLy8gU1BE
WC1MaWNlbnNlLUlkZW50aWZpZXI6IEdQTC0yLjAtb3ItbGF0ZXIKPiArLy8gQ29weXJpZ2h0IDIw
MjUgSUJNIENvcnAuCj4gKy9kdHMtdjEvOwo+ICsKPiArI2luY2x1ZGUgPGR0LWJpbmRpbmdzL2dw
aW8vYXNwZWVkLWdwaW8uaD4KPiArI2luY2x1ZGUgPGR0LWJpbmRpbmdzL2kyYy9pMmMuaD4KPiAr
I2luY2x1ZGUgPGR0LWJpbmRpbmdzL2xlZHMvbGVkcy1wY2E5NTV4Lmg+Cj4gKyNpbmNsdWRlICJh
c3BlZWQtZzYuZHRzaSIKPiArI2luY2x1ZGUgImlibS1wb3dlcjExLWR1YWwuZHRzaSIKPiArCj4g
Ky8gewo+ICvCoMKgwqDCoMKgwqDCoG1vZGVsID0gIkJhbGNvbmVzIjsKPiArwqDCoMKgwqDCoMKg
wqBjb21wYXRpYmxlID0gImlibSxiYWxjb25lcy1ibWMiLCAiYXNwZWVkLGFzdDI2MDAiOwo+ICsK
PiAKCi4uLgoKPiArfTsKPiArCj4gKyZpMmMwIHsKPiArwqDCoMKgwqDCoMKgwqBzdGF0dXMgPSAi
b2theSI7Cj4gKwo+ICvCoMKgwqDCoMKgwqDCoGVlcHJvbUA1MSB7Cj4gK8KgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoGNvbXBhdGlibGUgPSAiYXRtZWwsMjRjNjQiOwo+ICvCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqByZWcgPSA8MHg1MT47Cj4gK8KgwqDCoMKgwqDCoMKgfTsKPiAr
Cj4gK8KgwqDCoMKgwqDCoMKgZ3Bpb0AyMCB7CgpDYW4geW91IHBsZWFzZSBmb2xsb3cgdGhlIERU
UyBjb2Rpbmcgc3R5bGUgYW5kIG9yZGVyIHRoZSBub2RlcyBieSB1bml0CmFkZHJlc3M/CgpodHRw
czovL2RvY3Mua2VybmVsLm9yZy9kZXZpY2V0cmVlL2JpbmRpbmdzL2R0cy1jb2Rpbmctc3R5bGUu
aHRtbCNvcmRlci1vZi1ub2RlcwoKT3JkZXJpbmcgdGhlIHRvcC1sZXZlbCBsYWJlbCByZWZlcmVu
Y2VzIGFscGhhYmV0aWNhbGx5IHdvdWxkIGJlCmFwcHJlY2lhdGVkIHRvby4gSXQgZG9lc24ndCBz
ZWVtIGxpa2UgdGhleSdyZSBpbiBhbiBvcmRlciByZWZsZWN0aW5nCmUuZy4gdGhlIHVuaXQgYWRk
cmVzcywgaXQgZmVlbHMga2luZCBvZiBhcmJpdHJhcnkuCgo+ICvCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqBjb21wYXRpYmxlID0gInRpLHRjYTk1NTQiOwo+ICvCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqByZWcgPSA8MHgyMD47Cj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoGdwaW8tY29udHJvbGxlcjsKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgI2dw
aW8tY2VsbHMgPSA8Mj47Cj4gKwo+ICvCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqBncGlv
LWxpbmUtbmFtZXMgPQo+ICvCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgIiIsCj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqAiUlVTU0VMX0ZXX0kyQ19FTkFCTEVfTiIsCj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqAiUlVTU0VMX09QUEFORUxfUFJFU0VOQ0VfTiIsCj4gK8KgwqDC
oMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqAiQkxZVEhfT1BQQU5FTF9Q
UkVTRU5DRV9OIiwKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoCJDUFVfVFBNX0NBUkRfUFJFU0VOVF9OIiwKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoCIiLAo+ICvCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgIiIsCj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqAiREFTRF9CUF9QUkVTRU5UX04iOwo+ICvCoMKgwqDCoMKgwqDCoH07Cj4g
K307Cj4gKwoKLi4uCgo+ICsKPiArJmkyYzUgewo+ICvCoMKgwqDCoMKgwqDCoHN0YXR1cyA9ICJv
a2F5IjsKPiArCj4gK8KgwqDCoMKgwqDCoMKgZWVwcm9tQDUyIHsKPiArwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoMKgY29tcGF0aWJsZSA9ICJhdG1lbCwyNGM2NCI7Cj4gK8KgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoMKgwqDCoHJlZyA9IDwweDUyPjsKPiArwqDCoMKgwqDCoMKgwqB9Owo+ICsK
PiArwqDCoMKgwqDCoMKgwqB0ZW1wZXJhdHVyZS1zZW5zb3JANGUgewoKT3JkZXJpbmcgYWdhaW4g
aGVyZS4KCj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoGNvbXBhdGlibGUgPSAidGks
dG1wNDM1IjsKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgcmVnID0gPDB4NGU+Owo+
ICvCoMKgwqDCoMKgwqDCoH07Cj4gK307Cj4gCgouLi4KCj4gKwo+ICsma2NzMyB7Cj4gK8KgwqDC
oMKgwqDCoMKgc3RhdHVzID0gIm9rYXkiOwo+ICvCoMKgwqDCoMKgwqDCoGFzcGVlZCxscGMtaW8t
cmVnID0gPDB4Y2EyPjsKPiArwqDCoMKgwqDCoMKgwqBhc3BlZWQsbHBjLWludGVycnVwdHMgPSA8
MTEgSVJRX1RZUEVfTEVWRUxfTE9XPjsKPiArfTsKPiBkaWZmIC0tZ2l0IGEvYXJjaC9hcm0vYm9v
dC9kdHMvYXNwZWVkL2libS1wb3dlcjExLWR1YWwuZHRzaSBiL2FyY2gvYXJtL2Jvb3QvZHRzL2Fz
cGVlZC9pYm0tcG93ZXIxMS1kdWFsLmR0c2kKPiBuZXcgZmlsZSBtb2RlIDEwMDY0NAo+IGluZGV4
IDAwMDAwMDAwMDAwMDAuLmU1ZjY1MjU4ZTA4MmYKPiAtLS0gL2Rldi9udWxsCj4gKysrIGIvYXJj
aC9hcm0vYm9vdC9kdHMvYXNwZWVkL2libS1wb3dlcjExLWR1YWwuZHRzaQo+IEBAIC0wLDAgKzEs
Nzc5IEBACj4gKy8vIFNQRFgtTGljZW5zZS1JZGVudGlmaWVyOiBHUEwtMi4wLW9yLWxhdGVyCj4g
Ky8vIENvcHlyaWdodCAyMDI1IElCTSBDb3JwLgo+ICsKPiArLyB7Cj4gCgouLi4KCj4gKwo+ICsm
ZnNpbTAgewo+ICvCoMKgwqDCoMKgwqDCoCNhZGRyZXNzLWNlbGxzID0gPDI+Owo+ICvCoMKgwqDC
oMKgwqDCoCNzaXplLWNlbGxzID0gPDA+Owo+ICvCoMKgwqDCoMKgwqDCoHN0YXR1cyA9ICJva2F5
IjsKPiArwqDCoMKgwqDCoMKgwqBidXMtZnJlcXVlbmN5ID0gPDEwMDAwMDAwMD47Cj4gK8KgwqDC
oMKgwqDCoMKgY2ZhbS1yZXNldC1ncGlvcyA9IDwmZ3BpbzAgQVNQRUVEX0dQSU8oUSwgMCkgR1BJ
T19BQ1RJVkVfSElHSD47Cj4gKwo+ICvCoMKgwqDCoMKgwqDCoGNmYW1AMCwwIHsKPiArwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgcmVnID0gPDAgMD47Cj4gK8KgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoCNhZGRyZXNzLWNlbGxzID0gPDE+Owo+ICvCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqAjc2l6ZS1jZWxscyA9IDwxPjsKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgY2hpcC1pZCA9IDwwPjsKPiArCj4gK8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDC
oAoKLi4uCgo+ICsKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgc2JlZmlmb0AyNDAw
IHsKPiArwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoGNvbXBh
dGlibGUgPSAiaWJtLHA5LXNiZWZpZm8iOwo+ICvCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgcmVnID0gPDB4MjQwMCAweDQwMD47Cj4gKwo+ICvCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgb2NjIHsKPiArwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqBjb21wYXRp
YmxlID0gImlibSxwMTAtb2NjIjsKCkkgYXNzdW1lIHRoaXMgZG9lc24ndCBuZWVkIGEgbmV3IGNv
bXBhdGlibGUgZm9yIFAxMSAoZ2l2ZW4geW91J3JlCm1vdmluZyBpdCBvdXQgb2YgdGhlIHF1YWQg
RFRTSSkuCgpBbmRyZXcK


